dist: focal
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

before_install:
  - pip install -U pip build
  - pip install -r test-requirements.txt

install:
  - 'python setup.py build_ext --inplace --with-cython'

# commands to run tests
script:
  - PYTHONPATH=. py.test -v tests

notifications:
  email: false

cache:
  pip: true

branches:
  only:
    - master
