os: linux
dist: focal
language: python

jobs:
  include:
    - name: python 3.7 (amd64)
      python: "3.7"
      arch: amd64
    - name: python 3.8 (amd64)
      python: "3.8"
      arch: amd64
    - name: python 3.9 (amd64)
      python: "3.9"
      arch: amd64
    - name: python 3.10 (amd64)
      python: "3.10"
      arch: amd64

    - name: python 3.7 (arm64)
      python: "3.7"
      arch: arm64
    - name: python 3.8 (arm64)
      python: "3.8"
      arch: arm64
    - name: python 3.9 (arm64)
      python: "3.9"
      arch: arm64
    - name: python 3.10 (arm64)
      python: "3.10"
      arch: arm64

before_install:
  - pip install -U pip build
  - pip install -r test-requirements.txt

install:
  - "python setup.py build_ext --inplace --with-cython"

# commands to run tests
script:
  - PYTHONPATH=. py.test -v tests

notifications:
  email: false

cache:
  pip: true

branches:
  only:
    - master
