[tool.tbump]
# Uncomment this if your project is hosted on GitHub:
github_url = "https://github.com/zeromq/pyzmq"

[tool.tbump.version]
current = "2.0.0.dev"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (?P<pre>((a|b|rc|)\d+)|.dev\d*|)
  '''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

# For each file to patch, add a [[tool.tbump.file]] config
# section containing the path of the file, relative to the
# pyproject.toml location.

[[tool.tbump.file]]
src = "setup.py"
search = 'version="{current_version}"'

[[tool.tbump.file]]
src = "cyksuid/__version__.py"
search = '__version__: str = "{current_version}"'

[build-system]
requires = ["setuptools", "wheel", "packaging"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-verbosity = "1"

[tool.cibuildwheel.linux]
environment.CFLAGS = "-Wl,-strip-all"
environment.CXXFLAGS = "-Wl,-strip-all"

manylinux-aarch64-image = "manylinux2014"
musllinux-aarch64-image = "musllinux_1_1"
musllinux-i686-image = "musllinux_1_1"
musllinux-x86_64-image = "musllinux_1_1"


[tool.cibuildwheel.macos]
environment.MACOSX_DEPLOYMENT_TARGET = "10.9"

# mac-arm target is 10.15
[[tool.cibuildwheel.overrides]]
select = "*macos*{universal2,arm64}*"
environment.MACOSX_DEPLOYMENT_TARGET = "10.15"

# manylinux1 for old Python
[[tool.cibuildwheel.overrides]]
select = "cp3{67}-*"
manylinux-x86_64-image = "manylinux1"
manylinux-i686-image = "manylinux1"

# manylinux2010 for cp38-9, pp37-8
[[tool.cibuildwheel.overrides]]
select = "cp3{8,9}-* pp3{7,8}-*"
manylinux-x86_64-image = "manylinux2010"
manylinux-i686-image = "manylinux2010"

# manylinux2014 for cp310, pp39
[[tool.cibuildwheel.overrides]]
select = "cp310-* pp39-*"
manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"

# manylinux_2_28 for cp311
[[tool.cibuildwheel.overrides]]
select = "cp311-*"
manylinux-x86_64-image = "manylinux_2_28"
