name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  # only affects Windows, but easiest to set here for now
  SETUPTOOLS_ENABLE_FEATURES: "legacy-editable"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: macos-13
            python: "3.7"

          - os: macos-14
            python: "3.12"

          - os: macos-14
            python: "3.13"

          #- os: macos-13
          #  python: pypy-3.9

          - os: ubuntu-20.04
            python: "3.7"

          #- os: ubuntu-22.04
          #  python: pypy-3.9

          #- os: ubuntu-22.04
          #  python: pypy-3.7

          - os: ubuntu-22.04
            python: "3.9"

          - os: ubuntu-22.04
            python: "3.10"

          - os: ubuntu-22.04
            python: "3.11"

          - os: ubuntu-22.04
            python: "3.8"

          - os: ubuntu-22.04
            python: "3.12"

          - os: ubuntu-22.04
            python: "3.13"

          - os: ubuntu-22.04
            python: "3.13"

          - os: windows-2022
            python: "3.7"
            arch: x86

          - os: windows-2022
            python: "3.9"
            arch: x64

          - os: windows-2022
            python: "3.13"
            arch: x64

    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch || 'x64' }}
          allow-prereleases: true
          cache: pip

      - name: install dependencies
        run: |
          pip install --upgrade pip wheel setuptools
          pip install -r test-requirements.txt

      - name: show environment
        run: |
          pip freeze

      # preserve pip cache to speed up installation
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ runner.python }}-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: run coverage
        if: startsWith(matrix.python, 'pypy') == false
        run: |
          make coverage

      - name: run tests
        if: startsWith(matrix.python, 'pypy')
        run: |
          make test

      - name: upload coverage
        run: codecov
