# Stolen from pyzmq project
# PyZMQ is licensed under the terms of the Modified BSD License (also known as
# New or Revised BSD), as follows:
#
# Copyright (c) 2009-2012, Brian Granger, Min Ragan-Kelley
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright notice, this
# list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.
#
# Neither the name of PyZMQ nor the names of its contributors may be used to
# endorse or promote products derived from this software without specific prior
# written permission.
#
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

name: Release

on:
  push:
    branches:
      - master
    tags:
      - "v**"
  pull_request:
    paths:
      - setup.py
      - .github/workflows/wheels.yml
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  TWINE_NONINTERACTIVE: "1"

jobs:
  sdist:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: install dependencies
        run: |
          pip install --upgrade pip build pytest setuptools
          pip install -r tools/wheel-requirements.txt

      - name: build sdist
        run: |
          python setup.py build --with-cython
          python -m build --sdist .

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: "dist/*.tar.gz"
          if-no-files-found: error

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          pip install twine
          twine upload --skip-existing dist/*.tar.gz

  wheel:
    runs-on: ${{ matrix.os || 'ubuntu-22.04' }}

    env:
      MACOSX_DEPLOYMENT_TARGET: "10.9"
      CIBW_TEST_REQUIRES: "pytest"
      CIBW_TEST_COMMAND: "pytest -v {package}/tests"
      CIBW_BUILD: "${{ matrix.cibw.build || '*' }}"
      CIBW_SKIP: "${{ matrix.cibw.skip || '' }} pp*"  # skip building pypy wheels since broken (pypa/cibuildwheel#2015)
      CIBW_ARCHS: "${{ matrix.cibw.arch || 'auto' }}"
      CIBW_MANYLINUX_X86_64_IMAGE: "${{ matrix.cibw.manylinux_x86_64_image || '' }}"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-12
            name: mac-cpython
            cibw:
              build: "cp*"

          # - os: macos-12
          #   name: mac-pypy
          #   cibw:
          #     build: "pp*"

          - os: macos-14
            name: mac-arm
            cibw:
              arch: universal2
              build: "cp*"

          - name: manylinux-x86_64
            cibw:
              arch: x86_64
              build: "*manylinux*"

          - name: manylinux-i686
            cibw:
              arch: i686
              build: "*manylinux*"

          # additional manylinux variants, not specified in pyproject.toml:
          # build with newer 2_28 for cpython >= 3.10, pypy 3.9
          - name: manylinux-x86_64-2_28
            cibw:
              arch: x86_64
              build: "cp31*-manylinux* pp39-manylinux*"
              manylinux_x86_64_image: manylinux_2_28

          - name: musllinux
            cibw:
              build: "*musllinux*"

          - name: win32
            os: windows-2019
            architecture: x86
            cibw:
              build: "cp*win32"
              # free-threaded doesn't seem to work on Windows
              skip: "*t-win*"

          # - os: windows-2019
          #   name: win-pypy
          #   architecture: x64
          #   cibw:
          #     build: "pp*win_amd64"

          - os: windows-2019
            name: win_amd64
            architecture: x64
            cibw:
              build: "cp*win_amd64"
              # free-threaded doesn't seem to work on Windows
              skip: "*t-win*"

          - os: windows-2022
            name: win_arm64
            architecture: x64
            cibw:
              arch: ARM64
              # free-threaded doesn't seem to work on Windows
              skip: "cp37* *t-win*"


    steps:
      - uses: actions/checkout@v4

      # - name: Set up qemu
      #   id: qemu
      #   if: contains(matrix.os, 'ubuntu-') && matrix.cibw.arch == 'aarch64'
      #   uses: docker/setup-qemu-action@v1
      #   with:
      #     platforms: arm64

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: ${{ matrix.architecture }}

      - name: customize mac-arm-64
        if: contains(matrix.os, 'macos') && matrix.cibw.arch
        run: |
          echo 'MACOSX_DEPLOYMENT_TARGET=10.15' >> "$GITHUB_ENV"

      - name: install dependencies
        run: |
          pip install --upgrade setuptools pip wheel
          pip install -r tools/wheel-requirements.txt

      - name: show environment
        run: |
          pip freeze

      - name: list target wheels
        run: |
          python -m cibuildwheel . --print-build-identifiers

      - name: compile Cython sources
        run: |
          python setup.py build --with-cython

      - name: clean build
        if: contains(matrix.os, 'windows') == false
        run: |
          rm -rf build

      - name: build wheels
        run: |
          python -m cibuildwheel .

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.name }}
          path: "wheelhouse/*"
          if-no-files-found: error

      - name: Publish wheels to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          pip install twine
          twine upload --skip-existing wheelhouse/*
